version: "3"
services:
  hub:
    image: seleniarm/hub:4.1.2-20220227
    ports:
      - "4444:4444"
  chrome:
    image: seleniarm/node-chromium:4.1.2-20220227
    shm_size: '2g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: seleniarm/node-firefox:4.1.2-20220227
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  TestNg: 
    image: rinshadkt/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - MODULE=TestNg.xml
      - BROWSER=chrome 
      - HUB_HOST=hub

    volumes:
      - ./tests:/Users/rinshadkt/IdeaProjects/Container/test-output   